In [1]:
import numpy as np

In [2]:
# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

In [3]:
# XOR dataset
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outputs = np.array([[0], [1], [1], [0]])

In [4]:
# Seed for reproducibility
np.random.seed(42)

In [5]:
# Neural network architecture
input_layer_neurons = inputs.shape[1]  # Number of input features (2 for XOR)
hidden_layer_neurons = 2  # Number of neurons in the hidden layer
output_neurons = 1  # Single output for XOR

In [6]:
# Weights initialization
weights_input_hidden = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
weights_hidden_output = np.random.uniform(size=(hidden_layer_neurons, output_neurons))

In [7]:
# Bias initialization
bias_hidden = np.random.uniform(size=(1, hidden_layer_neurons))
bias_output = np.random.uniform(size=(1, output_neurons))

In [8]:
# Learning rate
learning_rate = 0.1

In [9]:
# Training the neural network
for epoch in range(10000):
    # Forward propagation
    hidden_layer_input = np.dot(inputs, weights_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_input)

    # Backpropagation
    error = outputs - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    # Updating weights and biases
    weights_hidden_output += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    weights_input_hidden += inputs.T.dot(d_hidden_layer) * learning_rate
    bias_output += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
    bias_hidden += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

In [10]:
# Testing the neural network
print("Final predicted output after training:")
print(predicted_output.round())

Final predicted output after training:
[[0.]
 [1.]
 [1.]
 [0.]]


In [11]:
print("\nFinal weights from input to hidden layer:")
print(weights_input_hidden)

print("\nFinal weights from hidden layer to output layer:")
print(weights_hidden_output)

print("\nFinal bias for hidden layer:")
print(bias_hidden)

print("\nFinal bias for output layer:")
print(bias_output)


Final weights from input to hidden layer:
[[3.6991303  5.699086  ]
 [3.70579679 5.73069504]]

Final weights from hidden layer to output layer:
[[-8.02663537]
 [ 7.42116082]]

Final bias for hidden layer:
[[-5.67051588 -2.37581163]]

Final bias for output layer:
[[-3.35000977]]
